"use client";

import React, { useState } from "react";
import {
  ShieldAlert,
  AlertTriangle,
  CheckCircle2,
  Info,
  Zap,
  Download,
  Sparkles,
  CheckSquare,
  Square,
  Clock,
} from "lucide-react";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "./ui/card";
import { Alert, AlertTitle, AlertDescription } from "./ui/alert";
import { Badge } from "./ui/badge";
import { Button } from "./ui/button";

interface ActionTask {
  id: string;
  priority: "P1 - Critical" | "P2 - High" | "P3 - Moderate" | "P4 - Advisory";
  title: string;
  description: string;
  fieldLocation: string;
  chemicalOrAction: string;
  deadline: string;
  status: "pending" | "in-progress" | "completed";
}

interface AiInsightsTabProps {
  onOpenReportModal: () => void;
}

export function AiInsightsTab({ onOpenReportModal }: AiInsightsTabProps) {
  const [tasks, setTasks] = useState<ActionTask[]>([
    {
      id: "task-1",
      priority: "P1 - Critical",
      title: "Apply Copper Hydroxide (77% WP) Tank-Mix",
      description: "Contain Early Blight (Alternaria solani) outbreak in Tomato Quad 4B before airborne sporangia disperse to adjacent rows.",
      fieldLocation: "Sector 4 - Tomato Quad 4B (340 Acres)",
      chemicalOrAction: "Copper Hydroxide 77% WP @ 2.0 lbs/acre",
      deadline: "Execute within 12 Hours",
      status: "pending",
    },
    {
      id: "task-2",
      priority: "P2 - High",
      title: "Adjust Canopy Drip Irrigation Flow Cycles",
      description: "Current canopy humidity is 84% RH with 22.4°C temperature. Reduce irrigation pulse by 30% to prevent Phytophthora spore germination.",
      fieldLocation: "Sector 2 & 4 - Tomato & Potato Borders",
      chemicalOrAction: "Automated Drip Valve Throttle -30%",
      deadline: "Execute within 24 Hours",
      status: "in-progress",
    },
    {
      id: "task-3",
      priority: "P3 - Moderate",
      title: "Deploy Azoxystrobin (22.9% SC) for Black Scurf",
      description: "Preventative tuber spray for Rhizoctonia solani in Potato Quad C.",
      fieldLocation: "Sector C - Potato Field (210 Acres)",
      chemicalOrAction: "Azoxystrobin 22.9% SC @ 0.8 fl oz/1000 ft",
      deadline: "Execute in 48 Hours",
      status: "pending",
    },
    {
      id: "task-4",
      priority: "P4 - Advisory",
      title: "Schedule Post-Spray OptiScan Drone Verification Sweep",
      description: "Rescan infected foliage 72 hours post-fungicide application to verify lesion regression.",
      fieldLocation: "All Active Quads",
      chemicalOrAction: "Automated Drone Flight Plan Alpha-9",
      deadline: "Scheduled for Day 3",
      status: "completed",
    },
  ]);

  const toggleTaskStatus = (id: string) => {
    setTasks((prev) =>
      prev.map((t) => {
        if (t.id === id) {
          const nextStatus =
            t.status === "pending"
              ? "in-progress"
              : t.status === "in-progress"
              ? "completed"
              : "pending";
          return { ...t, status: nextStatus };
        }
        return t;
      })
    );
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 rounded-2xl border border-emerald-500/20 bg-[#0B140D] p-6 shadow-xl">
        <div className="flex items-center gap-4">
          <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-emerald-500/20 border border-emerald-500/40 text-emerald-400 shadow-lg">
            <Sparkles className="h-7 w-7" />
          </div>
          <div>
            <h2 className="text-xl font-bold tracking-tight text-white flex items-center gap-2">
              AI Insights & Actionable Agronomy Plan
            </h2>
            <p className="text-xs text-emerald-400/70">
              Immediate, text-optimized action directives generated by Agri-Vision Neural Pathology Engine.
            </p>
          </div>
        </div>

        <Button onClick={onOpenReportModal} variant="emerald" className="gap-2 font-bold text-xs">
          <Download className="h-4 w-4" /> Export Official Agronomy Report
        </Button>
      </div>

      <div className="space-y-4">
        <h3 className="text-sm font-bold uppercase tracking-wider text-emerald-400 flex items-center gap-2">
          <ShieldAlert className="h-4 w-4 text-emerald-400" /> Immediate Threat Directives
        </h3>

        <Alert variant="destructive">
          <AlertTriangle className="h-5 w-5" />
          <div>
            <AlertTitle>
              CRITICAL DIRECTIVE: Tomato Early Blight (Alternaria solani) Spore Dispersal Threat
            </AlertTitle>
            <AlertDescription className="mt-1">
              Foliar scan <span className="font-mono font-bold">SCAN-8942</span> identified 68% risk severity across 340 acres in Sector 4B. High ambient humidity (84%) creates an optimal window for secondary infection. Apply <span className="font-semibold underline">Copper Hydroxide 77% WP</span> within 12 hours.
            </AlertDescription>
          </div>
        </Alert>

        <Alert variant="warning">
          <Info className="h-5 w-5" />
          <div>
            <AlertTitle>
              MICROCLIMATE WARNING: Phytophthora infestans Sporulation Vulnerability
            </AlertTitle>
            <AlertDescription className="mt-1">
              Nighttime temperature drops (18.2°C) combined with leaf wetness duration &gt; 6 hours increase Late Blight sporulation risk to 84%. Reduce overhead canopy irrigation immediately and prepare Mefenoxam tank mix.
            </AlertDescription>
          </div>
        </Alert>

        <Alert variant="success">
          <CheckCircle2 className="h-5 w-5" />
          <div>
            <AlertTitle>
              SUCCESSFUL VERIFICATION: Potato Main Quad A Cleared Pristine
            </AlertTitle>
            <AlertDescription className="mt-1">
              Optical scan <span className="font-mono font-bold">SCAN-8939</span> confirms 680 acres of Russet Burbank foliage remain 99.2% healthy with no detected lesions or fungal pathogens.
            </AlertDescription>
          </div>
        </Alert>

        <Alert variant="info">
          <Zap className="h-5 w-5" />
          <div>
            <AlertTitle>
              AGRONOMY RECOMMENDATION: Fungicide FRAC Rotation Schedule
            </AlertTitle>
            <AlertDescription className="mt-1">
              To prevent pathogen resistance buildup against Quinone Outside Inhibitors (QoI - FRAC 11), alternate next week&apos;s spray cycle with multi-site contact fungicide Chlorothalonil (FRAC M05).
            </AlertDescription>
          </div>
        </Alert>
      </div>

      <Card className="agri-glass-card">
        <CardHeader>
          <CardTitle className="text-base text-white flex items-center gap-2">
            <CheckSquare className="h-5 w-5 text-emerald-400" />
            Farmer Action Checklist & Intervention Timeline
          </CardTitle>
          <CardDescription>
            Click tasks to toggle intervention status: Pending &rarr; In-Progress &rarr; Completed.
          </CardDescription>
        </CardHeader>

        <CardContent className="space-y-3 p-5 pt-0">
          {tasks.map((task) => {
            const isDone = task.status === "completed";
            const isInProgress = task.status === "in-progress";

            return (
              <div
                key={task.id}
                onClick={() => toggleTaskStatus(task.id)}
                className={`group cursor-pointer rounded-xl border p-4 transition-all ${
                  isDone
                    ? "bg-emerald-950/20 border-emerald-900/30 opacity-70"
                    : isInProgress
                    ? "bg-amber-950/30 border-amber-500/40"
                    : "bg-[#0A120C] border-emerald-500/30 hover:border-emerald-400/50"
                }`}
              >
                <div className="flex items-start justify-between gap-3">
                  <div className="flex items-start gap-3">
                    <button className="mt-1 text-emerald-400">
                      {isDone ? (
                        <CheckSquare className="h-5 w-5 text-emerald-400 fill-emerald-950" />
                      ) : isInProgress ? (
                        <Clock className="h-5 w-5 text-amber-400 animate-spin" />
                      ) : (
                        <Square className="h-5 w-5 text-emerald-600" />
                      )}
                    </button>

                    <div>
                      <div className="flex items-center gap-2">
                        <span
                          className={`text-sm font-bold ${
                            isDone ? "line-through text-emerald-400/70" : "text-white"
                          }`}
                        >
                          {task.title}
                        </span>
                        <Badge
                          variant={
                            task.priority.includes("P1")
                              ? "destructive"
                              : task.priority.includes("P2")
                              ? "warning"
                              : "secondary"
                          }
                          className="text-[9px]"
                        >
                          {task.priority}
                        </Badge>
                      </div>

                      <p className="mt-1 text-xs text-emerald-200/80 leading-relaxed">
                        {task.description}
                      </p>

                      <div className="mt-2 flex flex-wrap items-center gap-4 text-[11px] font-mono text-emerald-400/70">
                        <span>Location: {task.fieldLocation}</span>
                        <span>Protocol: {task.chemicalOrAction}</span>
                      </div>
                    </div>
                  </div>

                  <div className="text-right shrink-0">
                    <Badge
                      variant={
                        isDone ? "success" : isInProgress ? "warning" : "outline"
                      }
                      className="text-[10px] uppercase font-mono"
                    >
                      {task.status}
                    </Badge>
                    <div className="mt-1 text-[10px] font-mono text-amber-300 font-semibold">
                      {task.deadline}
                    </div>
                  </div>
                </div>
              </div>
            );
          })}
        </CardContent>
      </Card>
    </div>
  );
}
